services:
  app:
    build:
      context: .
      target: final
    container_name: 'app-rust-rocket-restapi'
    platform: linux/amd64
    ports:
      - '18000:8000'
    depends_on:
      db:
        condition: service_healthy
    links:
      - grafana:grafana
    environment:
      - RUST_LOG=debug
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=rustrocketrestapi
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - JWT_SECRET=zNBH87*jhg^%)bjkhhkj
    networks:
      - rust-rocket-restapi

  db:
    image: mysql
    container_name: 'mysql-rust-rocket-restapi'
    platform: linux/amd64
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=rustrocketrestapi
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 15
    command: --init-file /data/application/init.sql
    volumes:
      - ./_db:/var/lib/mysql
      - ./sql/init.sql:/data/application/init.sql
    networks:
      - rust-rocket-restapi

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus-rust-rocket-restapi
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./_prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    labels:
      org.label-schema.group: "monitoring"
    networks:
      - rust-rocket-restapi

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    container_name: grafana-rust-rocket-restapi
    restart: unless-stopped
    ports:
      - '3000:3000'
    links:
      - prometheus:prometheus
    volumes:
      - ./_grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - rust-rocket-restapi

networks:
  rust-rocket-restapi:
