services:
  app:
    build:
      context: .
      target: final
    container_name: 'app-bookstore'
    platform: linux/amd64
    ports:
      - '18000:8000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RUST_LOG=debug
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bookstore
      - DB_USERNAME=root
      - DB_PASSWORD=12345678
      - JWT_SECRET=zNBH87*jhg^%)bjkhhkj
    networks:
      - bookstore

  db:
    image: mysql
    container_name: 'mysql-bookstore'
    platform: linux/amd64
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=bookstore
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 2s
      timeout: 3s
      retries: 15
    volumes:
      - ./_db:/var/lib/mysql
    networks:
      - bookstore

networks:
  bookstore:
